// <auto-generated />
using System;
using MauiBlazor.Shared.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MauiBlazor.Shared.Migrations
{
    [DbContext(typeof(出退勤DbContext))]
    [Migration("20250310060524_postgreInitialCreate")]
    partial class postgreInitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MauiBlazor.Shared.Models.社員", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("備考")
                        .HasColumnType("text");

                    b.Property<int>("入社年度")
                        .HasColumnType("integer");

                    b.Property<string>("名前")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("社員番号")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("社員番号")
                        .IsUnique();

                    b.ToTable("社員s");
                });

            modelBuilder.Entity("MauiBlazor.Shared.Models.社員カード", b =>
                {
                    b.Property<string>("カードUID")
                        .HasColumnType("text");

                    b.Property<string>("カード名称")
                        .HasColumnType("text");

                    b.Property<string>("備考")
                        .HasColumnType("text");

                    b.Property<int>("社員Id")
                        .HasColumnType("integer");

                    b.Property<string>("社員番号")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("追加日")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("カードUID");

                    b.HasIndex("社員Id");

                    b.ToTable("社員カードs");
                });

            modelBuilder.Entity("MauiBlazor.Shared.Models.社員打刻", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("備考")
                        .HasColumnType("text");

                    b.Property<DateOnly>("打刻日")
                        .HasColumnType("date");

                    b.Property<DateTime>("打刻時間")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("社員番号")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("社員打刻s");
                });

            modelBuilder.Entity("MauiBlazor.Shared.Models.社員カード", b =>
                {
                    b.HasOne("MauiBlazor.Shared.Models.社員", "社員")
                        .WithMany("社員カード")
                        .HasForeignKey("社員Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("社員");
                });

            modelBuilder.Entity("MauiBlazor.Shared.Models.社員", b =>
                {
                    b.Navigation("社員カード");
                });
#pragma warning restore 612, 618
        }
    }
}
